# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kalyco/Desktop/kalman_filter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kalyco/Desktop/kalman_filter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalyco/Desktop/kalman_filter/CMakeFiles /Users/kalyco/Desktop/kalman_filter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalyco/Desktop/kalman_filter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kalman

# Build rule for target.
kalman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kalman
.PHONY : kalman

# fast build rule for target.
kalman/fast:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/build
.PHONY : kalman/fast

KalmanFilter.o: KalmanFilter.cpp.o

.PHONY : KalmanFilter.o

# target to build an object file
KalmanFilter.cpp.o:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/KalmanFilter.cpp.o
.PHONY : KalmanFilter.cpp.o

KalmanFilter.i: KalmanFilter.cpp.i

.PHONY : KalmanFilter.i

# target to preprocess a source file
KalmanFilter.cpp.i:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/KalmanFilter.cpp.i
.PHONY : KalmanFilter.cpp.i

KalmanFilter.s: KalmanFilter.cpp.s

.PHONY : KalmanFilter.s

# target to generate assembly for a file
KalmanFilter.cpp.s:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/KalmanFilter.cpp.s
.PHONY : KalmanFilter.cpp.s

sail_prediction.o: sail_prediction.cpp.o

.PHONY : sail_prediction.o

# target to build an object file
sail_prediction.cpp.o:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/sail_prediction.cpp.o
.PHONY : sail_prediction.cpp.o

sail_prediction.i: sail_prediction.cpp.i

.PHONY : sail_prediction.i

# target to preprocess a source file
sail_prediction.cpp.i:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/sail_prediction.cpp.i
.PHONY : sail_prediction.cpp.i

sail_prediction.s: sail_prediction.cpp.s

.PHONY : sail_prediction.s

# target to generate assembly for a file
sail_prediction.cpp.s:
	$(MAKE) -f CMakeFiles/kalman.dir/build.make CMakeFiles/kalman.dir/sail_prediction.cpp.s
.PHONY : sail_prediction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kalman"
	@echo "... KalmanFilter.o"
	@echo "... KalmanFilter.i"
	@echo "... KalmanFilter.s"
	@echo "... sail_prediction.o"
	@echo "... sail_prediction.i"
	@echo "... sail_prediction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

